server:
  port: 80
  context-path: /spring-boot-quick-start
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        security: DEBUG

management:
  security:
    roles: ADMIN